/**
 * 
 */
package com.tmm.frm.domain.enums;

/**
 * Roles that any user can have
 * 
 * @author robert.hinds
 *
 */
public enum TransactionTag {
	CASHBACK, SALARY, INTEREST, PAYMENTS,
	
	DIRECTDEBIT, FEE, UTILITIES, WATER, GAS, ELECTRICITY, MOBILE, MORTGAGE, GROCERIES, DEPARTMENTSTORE, CASHWITHDRAWAL, CONVENIENCE, COUNCILTAX, 
	STANDINGORDER, INSURANCE, RENT, TRAVEL, HOLIDAY, SOCIAL, HEALTHCARE, ENTERTAINMENT, SPECIALOCCAION, CHRISTMAS, BIRTHDAY, SAVINGS,
	LIVINGEXPENSES, CHARITY, CLOTHING, PHONE, PENSION
}
